# Generated by Django 3.0.2 on 2020-01-04 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('item', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField()),
                ('transaction_type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=1)),
                ('necessary', models.BooleanField(default=False)),
            ],
        ),
    ]
