# Generated by Django 3.0.2 on 2020-01-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='D', max_length=1),
        ),
    ]
